# Generated by Django 5.2.4 on 2026-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField(help_text='Android version code (e.g., 5)')),
                ('version_name', models.CharField(help_text='Version name (e.g., 1.0.5)', max_length=50)),
                ('apk_url', models.URLField(help_text='URL to download the APK')),
                ('release_notes', models.TextField(blank=True, help_text='Release notes shown to the user')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Force user to update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active version?')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-version_code'],
            },
        ),
    ]
