# Generated by Django 4.2.29 on 2026-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Google Drive share/view link (e.g. https://drive.google.com/file/d/…/view)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4 video file (max 500 MB).', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://youtu.be/abc123 or https://youtube.com/watch?v=…)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='logo',
            field=models.ImageField(help_text='Thumbnail image shown on the video card.', upload_to='video_logos/'),
        ),
    ]
