List uniquecities = [
  "Poole",
  "Montreal",
  "Edmonton",
  "Hamilton",
  "London",
  "Victoria",
  "Toronto",
  "Guelph",
  "Ottawa",
  "St. Catharines",
  "Kingston",
  "Gaspe",
  "415 Yonge",
  "Montreal",
  "Prince George",
  "Wolfville",
  "Toronto",
  "Winnipeg",
  "North",
  "Melfort",
  "Oakville",
  "Thunder Bay",
  "Casa Loma",
  "London",
  "Wisconsin",
  "Vancouver",
  "Vancouver",
  "Halifax",
  "Belleville",
  "Kingston",
  "Toronto",
  "Burnaby",
  "Sarnia",
  "Windsor",
  "College Drive",
  "Sudbury",
  "Fennell",
  "Comox Valley",
  "Thunder Bay",
  "Swift Current",
  "Parkland",
  "New Westminster",
  "Alberta",
  "Barrie",
  "Calgary",
  "Colwood",
  "Oshawa",
  "Progress",
  "Saskatoon",
  "Montreal",
  "Sault",
  "Montreal",
  "Montreal",
  "North Bay",
  "Cranbrook",
  "Victoria Avenue",
  "Victoria",
  "Welland",
  "Coquitlam",
  "Saguenay",
  "Timmins",
  "Castlegar",
  "Fredericton",
  "Peterborough",
  "Calgary",
  "Barrydowne",
  "Dawson Creek",
  "London",
  "Edinburgh",
  "Manchester",
  "Strand",
  "Coventry",
  "Clifton",
  "Glasgow",
  "Southampton",
  "Durham City",
  "Birmingham",
  "St. Andrews",
  "Leeds",
  "Sheffield",
  "University Park",
  "Leeds",
  "Bailrigg",
  "Newcastle",
  "Devon",
  "Cardiff",
  "England",
  "Heslington",
  "Claverton Down",
  "Liverpool",
  "Aberdeen",
  "Brighton",
  "Epinal Way",
  "Leicester",
  "Guildford",
  "Glasgow",
  "Dundee",
  "Northampton Square",
  "Canterbury",
  "Falmouth",
  "London",
  "Colchester",
  "Singleton Park",
  "London",
  "Birmingham",
  "Stirling",
  "Hull",
  "Aberystwyth",
  "Bangor",
  "Coventry",
  "Plymouth",
  "England",
  "London",
  "Hull",
  "Portsmouth",
  "Newcastle",
  "City campus",
  "Huddersfield",
  "Park Row",
  "Keele",
  "Brighton",
  "Melbourne",
  "Palmerston",
  "London",
  "Auckland",
  "Carmarthen",
  "Penrhyn Road",
  "Manchester",
  "Lincoln",
  "Edinburgh",
  "Oncampus UK North",
  "Glasgow",
  "London",
  "Musselburgh",
  "Glasgow",
  "Derby",
  "Canterbury",
  "Wolverhampton",
  "Birmingham",
  "Worcester",
  "Birmingham",
  "Twickenham",
  "Oxford",
  "Plymouth",
  "London",
  "Melbourne",
  "Lincoln",
  "Hope",
  "Ipswich",
  "INTO",
  "Lincoln",
  "Bailrigg",
  "Singleton Park",
  "Oncampus London",
  "George St",
  "London",
  "Brighton",
  "Portsmouth",
  "INTO",
  "Velocity House",
  "London",
  "London",
  "Newton Park",
  "London",
  "Chester",
  "Bournemouth",
  "London",
  "Bournemouth",
  "London",
  "Rodney House",
  "Sunderland",
  "Friston",
  "Northampton",
  "Stoke-on-Trent",
  "Bolton",
  "England",
  "London",
  "Buckingham",
  "York",
  "Gloucestershire",
  "Aberdeen",
  "Liverpool",
  "Billinton Way",
  "Queen's Campus",
  "Reading",
  "Lancashire",
  "Cambridge Campus",
  "Carnegie Stand",
  "Nottingham",
  "INTO",
  "London",
  "Egham Hill",
  "Gloucestershire",
  "INTO",
  "London",
  "Colchester",
  "Guildford",
  "London",
  "Oncampus London",
  "Cambridge",
  "Sunderland",
  "Ormskirk",
  "East Park Terrace",
  "De Havilland",
  "Chichester",
  "Plymouth",
  "John St",
  "INTO",
  "Kingston Lane",
  "Penrhyn Rd",
  "London",
  "Guildford",
  "York",
  "Glasgow",
  "Wales",
  "City",
  "Leicester",
  "London",
  "Bristol",
  "Carlisle",
  "London",
  "Cranfield",
  "London",
  "Winchester",
  "Birmingham",
  "University Square",
  "Cambridge",
  "Stanford",
  "Cambridge",
  "Chicago",
  "Philadelphia",
  "New Haven",
  "Princeton",
  "Ithaca",
  "Evanston",
  "Berkeley",
  "Los Angeles",
  "Durham",
  "Rhode Island",
  "Madison",
  "Seattle",
  "Houston",
  "St. Louis",
  "West Lafayette",
  "Los Angeles",
  "Rochester",
  "Pittsburgh",
  "East Lansing",
  "Atlanta",
  "Minneapolis",
  "Nashville",
  "Washington",
  "Boulder",
  "Medford",
  "Tennessee",
  "Boston",
  "Santa Cruz",
  "Salt Lake City",
  "New York",
  "Denver",
  "Fort Collins",
  "Boston",
  "Athens",
  "River Forest",
  "Lincoln",
  "New York",
  "Albuquerque",
  "Philadelphia",
  "New Jersey",
  "Ypsilanti",
  "Waltham",
  "Seattle",
  "Tulsa",
  "Clinton",
  "Athens",
  "Utah",
  "Waco",
  "Stockton",
  "San Mateo",
  "Henniker",
  "Murray",
  "Bowling Green",
  "Maryville",
  "San Francisco",
  "Fayette",
  "Thousand Oaks",
  "Poughkeepsie",
  "Riverside",
  "New York City",
  "Providence",
  "Cape Girardeau",
  "Lakeland",
  "Lawrence Township",
  "Slippery Rock",
  "Oswego",
  "Bozeman",
  "Milwaukee",
  "Chicago",
  "Findlay",
  "Pittsburgh",
  "Los Angeles",
  "Dallas",
  "Greensboro",
  "New York",
  "Albany",
  "Raleigh",
  "Petersburg",
  "Vancouver",
  "Flagstaff",
  "Garden City",
  "Sioux City",
  "Madison",
  "Dayton",
  "Webster Groves",
  "Woodland Park",
  "Saint Paul",
  "Hamden",
  "East Greenwich",
  "Angola",
  "Belton",
  "Lincoln",
  "Tampa Bay",
  "Seattle",
  "Seattle",
  "Miami",
  "Harrisonburg",
  "Fort Worth",
  "New York City",
  "Lakewood",
  "Wichita Falls",
  "Reno",
  "Howell",
  "Parkland",
  "Auckland",
  "Wellington",
  "Christchruch",
  "Hamilton",
  "Invercargill",
  "Napier",
  "Rockhampton",
  "Adelaide",
  "Wollongong",
  "Perth",
  "Newcastle",
  "North Ryde",
  "Keiraville",
  "Victoria",
  "Queensland",
  "Melbourne",
  "Melbourne",
  "Gold Coast",
  "Melbourne",
  "Joondalup",
  "Toowoomba",
  "Armidale",
  "Adelaide",
  "Perth",
  "Adelaide",
  "Sydney",
  "Mt Helen",
  "Fremantle"
];
