# Generated by Django 5.2.4 on 2026-02-11 12:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Subject Code')),
                ('description', models.TextField(blank=True, verbose_name='Subject Description')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='Credits')),
                ('is_core', models.BooleanField(default=True, verbose_name='Core Subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Course Code')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='undergraduate', max_length=20)),
                ('duration', models.CharField(choices=[('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('4_years', '4 Years'), ('6_months', '6 Months'), ('1_semester', '1 Semester')], default='4_years', max_length=20)),
                ('credits', models.PositiveIntegerField(default=120, verbose_name='Total Credits')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tuition Fee')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('minimum_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Minimum GPA')),
                ('language_requirements', models.TextField(blank=True, verbose_name='Language Requirements')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Course')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popular Course')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Course Image')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='courses/brochures/', verbose_name='Course Brochure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('academic', 'Academic'), ('language', 'Language'), ('document', 'Document'), ('experience', 'Experience'), ('other', 'Other')], max_length=20, verbose_name='Requirement Type')),
                ('title', models.CharField(max_length=255, verbose_name='Requirement Title')),
                ('description', models.TextField(verbose_name='Requirement Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Mandatory Requirement')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Requirement',
                'verbose_name_plural': 'Course Requirements',
                'ordering': ['order', 'requirement_type'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tuition Fee')),
                ('tuition_fee_per_semester', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accommodation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Accommodation Fee')),
                ('meal_plan_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Meal Plan Fee')),
                ('transportation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Transportation Fee')),
                ('health_insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Health Insurance Fee')),
                ('books_materials_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Books & Materials Fee')),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Fees')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Payment Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='courses.course')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
            },
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='Semester')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optional Subject')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'verbose_name': 'Course Subject',
                'verbose_name_plural': 'Course Subjects',
                'unique_together': {('course', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseSubject', to='courses.subject'),
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('personal_statement', models.TextField(blank=True, verbose_name='Personal Statement')),
                ('expected_start_date', models.DateField(blank=True, null=True, verbose_name='Expected Start Date')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Application',
                'verbose_name_plural': 'Course Applications',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Rating',
                'verbose_name_plural': 'Course Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['university'], name='courses_cou_univers_5f4e01_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_cou_level_bf0a39_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
    ]
