# Generated by Django 5.2.4 on 2026-08-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('present', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=42)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='CLASS-001', max_length=50, unique=True)),
                ('name', models.CharField(default='Class 1', max_length=100)),
                ('program', models.CharField(default='Medical Entrance Program', max_length=200)),
                ('student_count', models.IntegerField(default=42)),
            ],
        ),
        migrations.CreateModel(
            name='MCQSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=1490)),
                ('questions_attempted', models.IntegerField(default=4280)),
                ('class_accuracy', models.IntegerField(default=82)),
                ('avg_questions_per_student', models.IntegerField(default=102)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('question_count', models.IntegerField(default=25)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('created', models.CharField(default='2026-07-20', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('roll', models.CharField(max_length=50)),
                ('attendance_percent', models.IntegerField(default=90)),
                ('mcq_attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='T-001', max_length=50, unique=True)),
                ('name', models.CharField(default='Dr. Anjali Menon', max_length=150)),
                ('email', models.EmailField(default='anjali.menon@example.edu', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher_cms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('student_answer', models.CharField(max_length=10)),
                ('correct_answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='teacher_cms.quizattempt')),
            ],
        ),
    ]
