# Generated by Django 5.2.4 on 2026-02-11 12:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Application Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('deferred', 'Deferred')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('intended_start_date', models.DateField(verbose_name='Intended Start Date')),
                ('intended_start_semester', models.CharField(max_length=20, verbose_name='Intended Start Semester')),
                ('academic_year', models.CharField(max_length=10, verbose_name='Academic Year')),
                ('personal_statement', models.TextField(blank=True, verbose_name='Personal Statement')),
                ('research_proposal', models.TextField(blank=True, verbose_name='Research Proposal')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='References')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Additional Information')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Decision Date')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Application Complete')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Application Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='universities.universityprogram')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('letter', 'Letter'), ('notification', 'In-App Notification')], max_length=20, verbose_name='Communication Type')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10, verbose_name='Direction')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='From Email')),
                ('to_email', models.EmailField(blank=True, max_length=254, verbose_name='To Email')),
                ('from_phone', models.CharField(blank=True, max_length=20, verbose_name='From Phone')),
                ('to_phone', models.CharField(blank=True, max_length=20, verbose_name='To Phone')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Communication',
                'verbose_name_plural': 'Application Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('transcript', 'Academic Transcript'), ('diploma', 'Diploma/Certificate'), ('passport', 'Passport'), ('visa', 'Visa'), ('ielts', 'IELTS Certificate'), ('toefl', 'TOEFL Certificate'), ('gre', 'GRE Score'), ('gmat', 'GMAT Score'), ('cv', 'CV/Resume'), ('personal_statement', 'Personal Statement'), ('research_proposal', 'Research Proposal'), ('reference_letter', 'Reference Letter'), ('financial_statement', 'Financial Statement'), ('medical_certificate', 'Medical Certificate'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('document_name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('file', models.FileField(upload_to='applications/documents/', verbose_name='Document File')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='File Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required Document')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Document Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['application', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('application_fee', 'Application Fee'), ('processing_fee', 'Processing Fee'), ('late_fee', 'Late Fee'), ('document_fee', 'Document Processing Fee'), ('interview_fee', 'Interview Fee'), ('other', 'Other')], max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Fee',
                'verbose_name_plural': 'Application Fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('in_person', 'In-Person Interview'), ('panel', 'Panel Interview'), ('technical', 'Technical Interview')], max_length=20, verbose_name='Interview Type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)')),
                ('interviewer_name', models.CharField(blank=True, max_length=255, verbose_name='Interviewer Name')),
                ('interviewer_email', models.EmailField(blank=True, max_length=254, verbose_name='Interviewer Email')),
                ('interviewer_phone', models.CharField(blank=True, max_length=20, verbose_name='Interviewer Phone')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Platform (for video interviews)')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Meeting Link')),
                ('preparation_notes', models.TextField(blank=True, verbose_name='Preparation Notes')),
                ('interview_notes', models.TextField(blank=True, verbose_name='Interview Notes')),
                ('feedback', models.TextField(blank=True, verbose_name='Interview Feedback')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Interview Score')),
                ('recommendation', models.CharField(blank=True, choices=[('strongly_recommend', 'Strongly Recommend'), ('recommend', 'Recommend'), ('neutral', 'Neutral'), ('not_recommend', 'Do Not Recommend'), ('strongly_not_recommend', 'Strongly Do Not Recommend')], max_length=22, verbose_name='Recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Interview',
                'verbose_name_plural': 'Application Interviews',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('deferred', 'Deferred')], max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
            ],
            options={
                'verbose_name': 'Application Status',
                'verbose_name_plural': 'Application Statuses',
                'ordering': ['-changed_at'],
            },
        ),
    ]
