"""
Django settings for edvoayge project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from urllib.parse import parse_qs, urlparse
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')

# Environment — never run production without DJANGO_SECRET_KEY set.
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-edzkool-production-key-937911240209-secret')

_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
    if 'hisham-final-submission.onrender.com' not in ALLOWED_HOSTS and '*' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('hisham-final-submission.onrender.com')
    if '*' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('*')
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '[::1]', '*']
else:
    ALLOWED_HOSTS = [
        'edvoyage.work.gd',
        'edzkool.publicvm.com',
        'edvoyage-backup-cursor-2.onrender.com',
        'edzkool.onrender.com',
        'hisham-final-submission.onrender.com',
        '.onrender.com',
        '107.23.198.71',
        '*',
    ]

ADMIN_URL = os.getenv('DJANGO_ADMIN_URL', 'edzkool-admin-panel/')

# Developer Mode for logging
DEVELOPER_MODE = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'rest_framework_simplejwt.token_blacklist',
    'axes',

    # Your apps
    'users',
    'universities',
    'courses',
    'applications',
    'notifications',
    'bookmarks',
    'payments',
    'quizzes',
    'content',
    'study_abroad',
    'timer',
    'ratings',
    'social',
    'search',
    'analytics',
    'web_integration',
    'notes',
    'simple_education',
    'cavity',
    'chatapp',
    'feed',
    'google_meet',
    'teacher_cms',
    'mailer',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'edvoayge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edvoayge.wsgi.application'

if os.name == "nt":
    POPPLER_PATH = r"C:\poppler\bin"
else:
    POPPLER_PATH = "/usr/bin"  # or wherever Poppler is installed


# Database
_DATABASE_URL = os.getenv("DATABASE_URL")
if _DATABASE_URL:
    _u = urlparse(_DATABASE_URL)
    _qs = parse_qs(_u.query)
    _opts = {}
    if "sslmode" in _qs and _qs["sslmode"]:
        _opts["sslmode"] = _qs["sslmode"][0]

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            'NAME': (_u.path or "").lstrip("/"),  # Use exact DB name from DATABASE_URL
            "USER": _u.username or "",
            "PASSWORD": _u.password or "",
            "HOST": _u.hostname or "",
            "PORT": str(_u.port or ""),
            "OPTIONS": _opts,
            "CONN_MAX_AGE": 600,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'edzkool_db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media / File Storage — AWS S3 (production) or local filesystem (development)
_USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'
USE_S3 = _USE_S3

if _USE_S3:
    AWS_ACCESS_KEY_ID       = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY   = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'edvoyage-edzkool-media')
    AWS_S3_REGION_NAME      = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    # Default to private objects; set AWS_DEFAULT_ACL=public-read only for legacy buckets.
    AWS_DEFAULT_ACL         = os.getenv('AWS_DEFAULT_ACL', 'private' if not DEBUG else 'public-read')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH    = AWS_DEFAULT_ACL != 'public-read'
    AWS_PRESIGNED_URL_EXPIRY = int(os.getenv('AWS_PRESIGNED_URL_EXPIRY', '3600'))
    AWS_LOCATION         = 'edzkool'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL  = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    MEDIA_ROOT = ''
else:
    # Local storage for development
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'auth': '10/minute',
    },
    'EXCEPTION_HANDLER': 'edvoayge.drf_exception_handler.standardized_exception_handler',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


CORS_URLS_REGEX = r'^/api/.*$|^/media/.*$'

CORS_ALLOW_METHODS = [
    'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
    'device-id', 'x-user-email',
]
CORS_EXPOSE_HEADERS = [
    'content-type', 'content-length', 'authorization', 'device-id',
    'x-user-email',
]
CORS_ALLOWED_ORIGINS = [
    "https://edvoyage.netlify.app",
    "https://edvoyage-backup-cursor.onrender.com",
    "https://edvoyage-backup-cursor-2.onrender.com",
    "https://edzkool.onrender.com",
    "https://edvoyage.duckdns.org",
    "https://edzkool.publicvm.com",
    "http://localhost:3000",
    "http://localhost:64806",
    "http://localhost:43489",
    "http://localhost:29726",
]
_cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '').strip()
if _cors_origins_env:
    _extra_cors = [o.strip() for o in _cors_origins_env.split(',') if o.strip()]
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(CORS_ALLOWED_ORIGINS + _extra_cors))

# Restrict CORS in production; allow all only during local DEBUG.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost:\d+$",
    r"^https?://127\.0\.0\.1:\d+$",
]


CSRF_TRUSTED_ORIGINS = [
    "https://edvoyage.netlify.app",
    "https://edvoyage-backup-cursor.onrender.com",
    "https://edvoyage-backup-cursor-2.onrender.com",
    "https://edzkool.onrender.com",
    "https://edvoyage.duckdns.org",
    "https://edzkool.publicvm.com",
    "http://54.234.68.39",
    "http://ec2-54-234-68-39.compute-1.amazonaws.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
_csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_origins_env:
    _extra_csrf = [o.strip() for o in _csrf_origins_env.split(',') if o.strip()]
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS + _extra_csrf))

# Logging Configuration
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}', 'style': '{'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'edzkool.log',
            'formatter': 'verbose',
        },
        'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console', 'file'], 'level': 'INFO'},
    'loggers': {'django': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False}},
}

# File Upload Settings
# Max 100 MB for uploads (Render free plan has 512MB RAM total)
# Large videos should use YouTube/GDrive URLs instead of direct upload.
MAX_UPLOAD_SIZE_MB = 100
MAX_UPLOAD_SIZE = MAX_UPLOAD_SIZE_MB * 1024 * 1024  # 104,857,600 bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
# Proxy / HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

# Cookie security
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG and SECURE_SSL_REDIRECT)).lower() == 'true'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG and SECURE_SSL_REDIRECT)).lower() == 'true'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# OTP test bypass — disabled in production (requires DEBUG=True and OTP_TEST_BYPASS=True)

OTP_TEST_BYPASS_CODE = os.getenv('OTP_TEST_BYPASS_CODE', '000000')

import logging as _logging
_logging.getLogger(__name__).warning(
        'OTP test bypass ENABLED — signup skips email; verify with code %s',
        OTP_TEST_BYPASS_CODE,
    )

# Custom User Model
# AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = [['ip_address', 'username']]
AXES_ENABLE_ADMIN = True

# Email Configuration
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')

EMAIL_HOST = os.getenv('EMAIL_HOST', 'email-smtp.us-east-1.amazonaws.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')


# Swagger Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {'type': 'apiKey', 'name': 'Authorization', 'in': 'header'}
    },
    'USE_SESSION_AUTH': False,
}

# CORS Configuration for Flutter Web and cross-origin requests
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
