# Generated by Django 5.2.4 on 2026-02-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_courses', to='courses.course')),
            ],
            options={
                'verbose_name': 'Favourite Course',
                'verbose_name_plural': 'Favourite Courses',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'course')},
            },
        ),
        migrations.CreateModel(
            name='FavouriteUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_universities', to='universities.university')),
            ],
            options={
                'verbose_name': 'Favourite University',
                'verbose_name_plural': 'Favourite Universities',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'university')},
            },
        ),
    ]
